#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          5

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#8b0000"
bspc config urgent_border_color "#FF0000"
bspc config presel_border_color "#26E2FF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# Make Lemonbar a floating window and ensure it doesn't take up space
bspc rule -a lemonbar state=floating

# set the background img
feh --bg-scale ~/Images/windows-linux.jpg
dunst --print &
~/.config/lemonbar/lemonbar.sh | lemonbar  -f "Noto Sans" &
